name: Fuzz Testing
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'COPYRIGHT'
      - 'LICENSE*'
      - '**.md'
      - '**.txt'
      - 'art'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'COPYRIGHT'
      - 'LICENSE*'
      - '**.md'
      - '**.txt'
      - 'art'
  schedule: [cron: "0 1 */7 * *"]
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Run fuzzing
        run: |
          cargo fuzz build
          cargo fuzz run fuzz -- -max_total_time=300
