name: test borsh
run-name: ${{ github.actor }}'s patch
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          toolchain: nightly
      - run: |
          cargo test --no-default-features --features=borsh
          cargo test --no-default-features --features=borsh,std
